### ISSUE TITLE
sdist published on pypi lacks template files

### ISSUE THREAD

**Issue by mypalmike** [jeffknupp/sandman2#17]
The current sdist distribution on pypi (0.0.6) has a bug where it lacks the template files needed for the admin interface. It was built without the necessary "setuptools-git" package installed on the machine that built it.

Until a new build is released, a workaround for end-users is:

pip install setuptools-git
git clone https://github.com/jeffknupp/sandman2.git
cd sandman2
python setup.py sdist
cd dist
pip install --force sandman2-0.0.6.tar.gz

**Comment by jeffknupp** [comment]
Fixed in version 0.0.7
