### ISSUE TITLE
Can Not Connect To Sql server

### ISSUE THREAD

**Issue by uditvishnoi** [jeffknupp/sandman2#22]
Hey , i am not bale to connect to Sql server database , i am new to python . I am getting this error 

 File "pymssql.pyx", line 639, in pymssql.connect (pymssql.c:10246)
sqlalchemy.exc.InterfaceError: (pymssql.InterfaceError) Connection to the database failed for an unknown reason.

I am using this commmand to connect to sql server 
sandmanctl mssql+pymssql://username:password@servername/database

**Comment by filmackay** [comment]
Personally, I would use pyodbc instead. newer things (AlwaysOn availability etc.) are really only supported with ODBC.

What platform are you connecting from?

**Comment by jeffknupp** [comment]
This doesn't appear to be a sandman issue, but rather an issue with the underlying database library. Are you able to connect to your database using the library in the "normal" way?
