### ISSUE TITLE
More REST query patterns

### ISSUE THREAD

**Issue by filmackay** [jeffknupp/sandman2#23]
Just wondering what people's thoughts are on implementing more complex patterns for reading (joins and filters), along the lines of things like:

- joins: /table1/id1/table2 - returns all the table2's related to table1 key id1
- filters: /table1?id=id1 - alternative to /table1/id1
- sort: /table1?_orderby=field1,field2
- pagination: /table1?_size=100&page=1

(http://sailsjs.org/documentation/reference/blueprint-api for some ideas)

At some point it is easier to parse the URL, rather than prepare every conceivable pattern. Thoughts?

**Comment by filmackay** [comment]
Realised just now that filter, sort, pagination is already supported - just not documented, is that right - or are they placeholder / partial implementations?

**Comment by jeffknupp** [comment]
Nope, they're fully supported. I'll be sure to update the docs as soon as I can.

**Comment by filmackay** [comment]
What about joins - a-la /table1/id1/table2 - I couldn't see them in there?
