### ISSUE TITLE
Versioning & Anaconda

### ISSUE THREAD

**Issue by filmackay** [jeffknupp/sandman2#26]
Would it be possible to label the versions in git? This would really help in creating a nice build for conda package manager, which integrates quite well with labels.

While I'm on that topic: would you be open to a PR that includes a conda recipe? This would allow someone to easily package up this library into an Anaconda package, which adds some meta-data on-top of what's already in setup.py?

It consists of a single file (meta.yaml) in the root.

**Comment by jeffknupp** [comment]
Would certainly be open to a conda recipe. Will also start tagging versions in git.
