### ISSUE TITLE
maturity stage of sandman2

### ISSUE THREAD

**Issue by lerrua** [jeffknupp/sandman2#27]
Hi there,

What is the current maturity level of sandman2? Can it be used in production or should be better to use sandman1?

**Comment by kuthair** [comment]
Hi. I work for a large company. We are using Sandman2 in production and have had minimal issues with it.

We had to modify it a bit to support a multi-tenant system.

**Comment by jeffknupp** [comment]
@lerrua: It depends. Both projects are mature enough to be used in production. `sandman2` is not at feature parity with `sandman` (and I may choose to drop support for some `sandman` features) but `sandman` will not be supported/actively developed going forward.

**Comment by lerrua** [comment]
thank you so much :+1:
