### ISSUE TITLE
Different Schema?

### ISSUE THREAD

**Issue by dmofot** [jeffknupp/sandman2#29]
@jeffknupp - Is it possible to use sandman2 with a schema other than **public**?

**Comment by ralienpp** [comment]
I think I'm running into a similar problem - your web-ui does not list any tables at all, is that correct?

**Comment by jeffknupp** [comment]
@dmofot @ralienpp I can add that ability. Are you using `sandman2ctl` or extending the code directly?

**Comment by pmart123** [comment]
@jeffknupp It'd be nice from the command line as an argument.

**Comment by generalelectrix** [comment]
+1 for this feature, I'm very interested in using this library but without schema support I'm dead in the water.

**Comment by dmofot** [comment]
Hey @jeffknupp , sorry I missed your post.  If it was possible for `sandmand2ctl` to have an option for doing the equivalent of 
```sql
SET search_path TO my_schema, public;
```
it would certainly make accessing data outside the `public` schema a lot easier.

**Comment by generalelectrix** [comment]
It was trivial to ask SQLAlchemy to use a different schema besides public.  Not sure if multiple schema specifications are possible, but this PR I just filed adds support for at least selecting a schema: https://github.com/jeffknupp/sandman2/pull/42

**Comment by jeffknupp** [comment]
Closed by #42
