### ISSUE TITLE
sqlalchemy_utils.PasswordType makes JSONEncoder's serialization barf

### ISSUE THREAD

**Issue by Datamance** [jeffknupp/sandman2#37]
Here's my stacktrace:

```
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/json.py", line 83, in default
    return _json.JSONEncoder.default(self, o)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'$2a$12$0rN/M0JPI3ChHNlxBnhoqeNyaC95otDUbflNsjY5O9XvEAlLiUETi' is not JSON serializable
```

You just might wanna make the api machinery a little more robust, to handle bytes serialization.

**Comment by jeffknupp** [comment]
JSON, as a format, does not have a way to encode arbitrary binary data. That's a limit of the format, not the API.

**Comment by Datamance** [comment]
@jeffknupp then maybe have default serialization for binary data properties turned off? I'm guessing that you're going to have other devs who want to get user data from databases that use bcrypt to protect passwords.

I'm assuming this is something I can get around by extending sandman2.model.Model?

**Comment by jeffknupp** [comment]
Yes, the proper way to address this would be to extend `sandman2.model.Model`. I'm 👎 on excluding types from serialization as it would either require a catch-all rule that would be difficult to maintain or an explicit list of (database-specific) excluded types which would be even more error-prone.
