### ISSUE TITLE
No tables read from sqlite3 file

### ISSUE THREAD

**Issue by agordon** [jeffknupp/sandman2#39]
Hello,

On some sqlite3 tables, it seems sandman2 is unable to discover the names of the tables, and presents empty list on the admin page (and returns 'not found' for all tables).

Example:
```
$ echo "create table foo(a integer); insert into foo values (1),(2),(3);" | sqlite3  bar.sqlite3
$ echo "select * from foo;" | sqlite3 bar.sqlite3 
1
2
3
$ sandman2ctl sqlite+pysqlite:///bar.sqlite3
```

Visiting "localhost:5000/admin" shows no tables at all.
No errors are displayed on the terminal, either.

Any ideas how to solve this?

The installed versions are:
```
$ pip freeze | grep -Ei 'sandman|sql|flask'
Flask==0.11.1
Flask-Admin==1.4.2
Flask-HTTPAuth==3.1.2
Flask-SQLAlchemy==2.1
SQLAlchemy==1.0.14
pysqlite==2.6.3
sandman2==0.0.7
```

Thanks!

**Comment by jeffknupp** [comment]
it's likely due to the table not having a primary key, which SQLAlchemy doesn't support (and REST APIs generally aren't compatible with either). I'll check why it's not raising an `Exception`

**Comment by agordon** [comment]
Thanks for the quick response! Adding a primary key indeed solved the issue.

BTW, there's also no indication if one specifies a non-existing sqlite3 file. I know 'sqlite3' can autocreate the file if it doesn't exist, but without any indication (and showing no tables in either way) - it's a bit confusing to troubleshoot.

In any case, thanks for a fantastic program!
