### ISSUE TITLE
Missing example

### ISSUE THREAD

**Issue by lrrb** [jeffknupp/sandman2#44]
Hello,

Sandman2 is a great piece of software for those with little knowledge in programming like myself. However, it's sometime necessary to change the default behavior of the software. Sandman1 documentation  came with some examples for that. Is there something as good as that for sandman2 ?

Thank you very much

**Comment by jeffknupp** [comment]
Yes! I've simply left it out of the repo up to this point. I'll add it and expand on the examples I have a bit.

**Comment by ahujamoh** [comment]
@jeffknupp I have tested my code locally working with postgresql. This can serve as an example.

    from sandman2 import app
    SQLALCHEMY_DATABASE_URI = 'postgresql:///chinook'
    myapp = app.get_app(SQLALCHEMY_DATABASE_URI)
    myapp.run()

**Comment by jeffknupp** [comment]
There are now examples in the `/examples` directory.
