### ISSUE TITLE
does update_version.sh update setup.py?

### ISSUE THREAD

**Issue by swharden** [jeffknupp/sandman2#53]
[setup.py has a plain text version string](https://github.com/jeffknupp/sandman2/blob/47ac844be564f1390fc5177557b1907b65e7f453/setup.py#L39) which I don't think will be updated by [update_version.sh](https://github.com/jeffknupp/sandman2/blob/master/update_version.sh). It is very different in sandman2 vs sandman(1).

in the update script I wonder if the -r in the line does this somehow:
`python setup.py sdist bdist_wheel upload -r pypi`
but [the pypi page](https://pypi.python.org/pypi/sandman2) lists the version in setup.py so I'm not sure.

This update script looks very important and convenient! A line or two of documentation on what it does would help a lot.

**Comment by jeffknupp** [comment]
the `update_version` script is out of date and shouldn't be used (I'm going to remove it right now). Version is taken solely from `setup.py`.
