### ISSUE TITLE
sqlite db displays on {} on http://0.0.0.0:5000/

### ISSUE THREAD

**Issue by MortalCatalyst** [jeffknupp/sandman2#56]
Following the instructions on the main githiub page I attempt to connect to a small db that I have started creating. However I am receiving only when I open the localhost

> {}

I am in the same directory and connect to the db race.db you can see here in this structure, I connect no errors just am not receiving the expected output.

```bash
sayth@linux-2sg8:~/xml/XML_race_dict> ll
total 104
-rw-r--r-- 1 sayth users 86434 Mar  6 13:33 mycsv.csv
-rw-r--r-- 1 sayth users     0 Mar  6 13:38 race
-rw-r--r-- 1 sayth users  8192 Mar  6 13:33 race.db
-rw-r--r-- 1 sayth users  4228 Mar  6 13:33 xml_race.py
sayth@linux-2sg8:~/xml/XML_race_dict> sandman2ctl sqlite+pysqlite:///race.db
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Mar/2017 13:40:28] "GET /race HTTP/1.1" 404 -
127.0.0.1 - - [06/Mar/2017 13:40:33] "GET / HTTP/1.1" 200 -
```

Not sure what would help so to show db has valid data I pulled it console using sql2csv.

```bash
sayth@linux-2sg8:~/xml/XML_race_dict> sql2csv --db "sqlite:///race.db" --query "select * from race"
R_Number,R_KEY,R_NAME,R_AGE,R_DIST,R_CLASS,M_ID
1,227392,BENCHMARK 85 HCP,3U,2000,BM85,46295
2,227393,TAB HIGHWAY PLATE,3U,1600,CL3,46295
3,227394,SWEET EMBRACE STAKES,2,1200,~,46295
4,227395,SKYLINE STAKES,2,1200,~,46295
5,227396,LIVERPOOL CITY CUP,3U,1300,~,46295
6,227397,SURROUND STAKES,3,1400,~,46295
7,227398,CHIPPING NORTON STAKES,3U,1600,~,46295
8,227399,GUY WALTER STAKES,4U,1400,~,46295
9,227400,BENCHMARK 85 HCP,3U,1200,BM85,46295
sayth@linux-2sg8:~/xml/XML_race_dict> 
```

**Comment by jeffknupp** [comment]
That's quite odd. Is `race.db` something you would be comfortable attaching so I can investigate more?

**Comment by MortalCatalyst** [comment]
[race.db.zip](https://github.com/jeffknupp/sandman2/files/824257/race.db.zip)

**Comment by jeffknupp** [comment]
Ah. The problem here is that there are no primary keys defined. Without a primary key, it's not really possible to create a REST API as there's no way to uniquely refer to an individual resource.

**Comment by MortalCatalyst** [comment]
Ah okay easy fixed on my end. Thanks.
