### ISSUE TITLE
Paging does not work with MSSQL

### ISSUE THREAD

**Issue by knutimar** [jeffknupp/sandman2#61]
http://localhost:5000/bigtable/?page=1 works
http://localhost:5000/bigtable/?page=2 gives 500 Internal Server Error

....
sql/base.py", line 1169, in visit_select
    raise exc.CompileError('MSSQL requires an order_by when '
CompileError: MSSQL requires an order_by when using an OFFSET or a non-simple LIMIT clause

I am using sandman2 v1.0.6 and Python 2.7.12 on Linux
Connection string starts with mssql+pymssql://

**Comment by jeffknupp** [comment]
Well, the error seems clear and makes sense. Let me see what I can do. Unfortunately, I don't have an MSSQL database to test on, but it should work on any database.

**Comment by jeffknupp** [comment]
@knutimar In the meantime, can you try to circumvent this by simply adding `/?sort=<some attribute of your model>&page=2` and let me know the output?

**Comment by knutimar** [comment]
Hi, thanks for your reply.
The workaround with adding /?sort=<some attribute of your model>&page=2 works
fine, thank you!
I tried several increments for page=x and every time I get 20 new elements.

2017-05-16 15:55 GMT+02:00 Jeff Knupp <notifications@github.com>:

**Comment by jeffknupp** [comment]
20 is just the default. If you'd like to change the number returned per page, set the `limit` URL parameter
