### ISSUE TITLE
How would one add authentication to sandman2 (either basic or oauth) (feature request)

### ISSUE THREAD

**Issue by tlawork** [jeffknupp/sandman2#62]
How would you add authentication to sandman2?
I only want to allow one particular user with a token or huge password to be able to update or access the database.

---TODDL

**Comment by ShyftXero** [comment]
I am still looking into getting a functioning PR for basic http auth but in the meantime I have nginx running a proxy pass with htpasswd authentication 
`
#added for sandman2ctl rest api
location /api/ {
  proxy_pass http://localhost:3000/;
  auth_basic "Restricted Content";
  auth_basic_user_file /etc/nginx/api.htpasswd;
}`
run sandman sandman2ctl -p 3000 &lt;dbconnstring>

from these directions
[https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-nginx-on-ubuntu-14-04](url)
