### ISSUE TITLE
Including relational data?

### ISSUE THREAD

**Issue by jcrben** [jeffknupp/sandman2#65]
I was messing around with PostgREST before this and they have the concept of resource embedding to pull in related data. Is there anything similar here? It also seems like https://github.com/pyeve/eve-sqlalchemy supports this.

With sandman(1), it seems like the docs suggest that there should be links - altho there is a field named links, it's not clear how that relates to items:
![image](https://user-images.githubusercontent.com/5614134/32151347-6f7407a4-bcd9-11e7-8936-70c1062bff66.png)

With sandman2, I don't even see a link:
![image](https://user-images.githubusercontent.com/5614134/32151380-9ae5585c-bcd9-11e7-9c84-12483e7033af.png)

Schema constructed with a simple many-to-many relationship:
```
users_items_assoc = Table('users_items_assoc', Base.metadata,
                          Column('users_items_assoc_id', Integer, primary_key=True),
                          Column('user_id', Integer, ForeignKey('users.id')),
                          Column('item_id', Integer, ForeignKey('items.id'))
                          )

class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    nickname = Column(String)

    items = relationship('Item', back_populates='users', secondary=users_items_assoc)

    def __repr__(self):
        return f'{self.name}'


class Item(Base):
    __tablename__ = 'items'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    description = Column(String)

    users = relationship('User', back_populates='items', secondary=users_items_assoc)
    # TODO: add image, upc, and so on

    def __repr__(self):
        return f'{self.name}'
```

**Comment by jcrben** [comment]
Closing this as I have decided not to use this library.

**Comment by rrjanbiah** [comment]
Same question here.

@jcrben What library or approach did you choose?

**Comment by rrjanbiah** [comment]
@jeffknupp Thank you!

**Comment by mrhaoji** [comment]
Where can I find the "Link Header"? in the response Header? @jeffknupp
