### ISSUE TITLE
Distribute as docker images

### ISSUE THREAD

**Issue by pscanf** [jeffknupp/sandman2#75]
Last year I started using sandman2 at my company for building a quick admin console. Since we use docker to deploy things, and since the project doesn't provide official docker images, I dockerized it myself and published the image on [docker hub](https://hub.docker.com/r/mondora/sandman2-mssql/).

The image (which only targets mssql) has since been downloaded 100k+ times, probably because it's the first result when [searching for **sandman**](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=sandman&starCount=0) on docker hub.

A couple of days ago I received [a PR on the docker image repo](https://github.com/mondora/docker-sandman2-mssql/pull/1) to update some dependencies, but I'm hesitant to merge it to master because the update could potentially break existing users (back when I created the image I didn't think about setting up a versioning scheme for it, so everything that goes into the master branch of the repo gets published as the `latest` tag of the docker image).

So to get to the point, since there appears to be some demand for a dockerized version of sandman2, you might want to consider directly publishing images for it.

**Comment by jeffknupp** [comment]
Will do. Thanks so much for the head's up. I'll update this issue when official image is out.

**Comment by pscanf** [comment]
```sh
#!/bin/sh

# Register DSN
odbcinst -i -s -l -r <<EOF
[DefaultDataSource]
Driver      = ${MSSQL_ODBC_DRIVER-ODBC Driver 13 for SQL Server}
Server      = $MSSQL_HOSTNAME,${MSSQL_PORT-1433}
Database    = $MSSQL_DATABASE_NAME
EOF

# Start sandman2
sandman2ctl -p $PORT mssql+pyodbc://$MSSQL_USERNAME:$MSSQL_PASSWORD@DefaultDataSource
```

You can find it in the repo from which the image builds: https://github.com/mondora/docker-sandman2-mssql/blob/master/start.sh
