### ISSUE TITLE
Current develop

### ISSUE THREAD

**Issue by therden** [jeffknupp/sandman2#90]
I noticed that you recently began working on `Sandman2` again, and thought that it might therefore be okay to ask:  Is having `Sandman2` achieve feature parity with `Sandman` still a goal, or have you concluded in the intervening years that the features of the original which it lacks are not worth having, or...?

(I'm wondering because I find it confusing that the original `Sandman` repo's README identifies that version as "obsolete" while `Sandman2`'s README indicates that it has an incomplete feature set compared to the first.)

**Comment by jeffknupp** [comment]
I'll update the README. `sandman2` has long ago passed the feature set of `sandman`.
